all:
	javac deepspace/TestP2.java	
	@echo " ========== resultado ejecución ============= "
	java deepspace/TestP2
test1:
	javac deepspace/TestP1.java
	@echo " ========== resultado ejecución ============= "
	java deepspace/TestP1

test2:
	javac deepspace/TestP2.java
	@echo " ========== resultado ejecución ============= "
	java deepspace/TestP2

clear:
	rm deepspace/*.class
	rm deepspace/*~
