/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.EnemyToUI;
/**
 *
 * @author usuario
 */
public class EnemyView extends javax.swing.JPanel {

    private LootView lootView;
    
    /**
     * Creates new form EnemyView
     */
    public EnemyView() {
        lootView=new LootView();
        initComponents();
        
        
        revalidate();
        repaint();
        
    }
    
    void setEnemy(EnemyToUI e){
        //.out.println("Debería pintar un enemigo");
        nombre.setText(e.getName());
        jLpotenciaDefensa.setText(Float.toString(e.getShieldPower()) );
        jLpotenciaFuego.setText(Float.toString(e.getAmmoPower()));
        lootView.setLoot(e.getLoot());
        jPLoot.add(lootView);
        jPLoot.setVisible(true);
        revalidate();
        repaint();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLpotenciaFuego = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLpotenciaDefensa = new javax.swing.JLabel();
        jPLoot = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Enemigo:");

        nombre.setText("jLabel2");

        jLabel2.setText("Potencia de Fuego:");

        jLpotenciaFuego.setText("jLabel3");

        jLabel3.setText("Potencia de defensa: ");

        jLpotenciaDefensa.setText("jLabel4");

        jLabel4.setText("Loot");
        jPLoot.add(jLabel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLpotenciaDefensa)
                            .addComponent(jLpotenciaFuego)))
                    .addComponent(jPLoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLpotenciaFuego))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLpotenciaDefensa))
                .addGap(18, 18, 18)
                .addComponent(jPLoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLpotenciaDefensa;
    private javax.swing.JLabel jLpotenciaFuego;
    private javax.swing.JPanel jPLoot;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
